In [2]:
import numpy

In [3]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n1 = n.reshape(3,9)
n1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [11]:
import cv2 #cv2 is the library OpenCV which is the library used for image processing

In [15]:
img = cv2.imread("smallgray.png",0) # 0 dictates the image will be loaded in grey scale
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
#the array is 3 x 5 which matches the image (had 15 pixels)
# the value directly dictates the intensity of the pixel (it can be seen that the higher the number the more white the pixel in this case)
# 0 is equal to black and 255 is white and everything inbetween is a type of grey

In [19]:
img2 = cv2.imread("smallgray.png",1)
img2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [20]:
# as you can see from above, when changing the second argument to 1 and loading the image in BGR, it gives a 3D array
# each array dictates the strength of that colour in the order of Blue Green and Red respectively

In [22]:
cv2.imwrite("newsmallgray.png", img)

True

In [23]:
#Slicing numpy arrays is very simple

In [25]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
img[0:2 , 1:4]  #indexes followed by columns

array([[158, 104, 121],
       [125, 255, 255]], dtype=uint8)

In [29]:
imgs = numpy.hstack((img,img))
imgs

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [32]:
imgs2 = numpy.vstack((img,img))
imgs2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [34]:
lst =numpy.hsplit(imgs2, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [36]:
lst2 = numpy.vsplit(imgs2, 3)
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [37]:
# think of v split, as cutting the array sideways with a knife and  h split as cutting it downwards ( so its almost antagonistic pairs)